### ISSUE TITLE
Cleanup .travis.yml

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/xcsharp#232]
The `.travis.yml` file has been cleaned-up immensely due to the recent .NET Core changes. However, there are still a couple of lines that can probably be removed. More specifically, these lines can be removed:

```yaml
sudo: required
os:
  - linux
```
